WebProje/Controllers/CustomerController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using EntityLayer.Concrete;
using Route = EntityLayer.Concrete.Route;

namespace WebProje.Controllers
{
	[Authorize]
	public class CustomerController : Controller
	{
		
		[HttpGet]
		public IActionResult Index()
		{
			RouteManager rm = new RouteManager(new EfIRoute());
			var routes=rm.GetRoutes();

			return View(routes);
		}
        [HttpPost]
        public IActionResult Index(Route route)
        {
           if(ModelState.IsValid)
			{
				return RedirectToAction("Index");
			}
			else
			{
				return View();
			}
        }
    }
}

WebProje/Controllers/SeatController.cs
using DataAccessLayer.Concrete;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace WebProje.Controllers
{
    public class SeatController : Controller
    {
        Context c=new Context();
        public IActionResult Index()
        {
            var seats=c.Seats.ToList();
            return View(seats);
        }
        [HttpPost]
        public IActionResult Index(int selectedRouteID)
        {
			//var selectedRoute = c.Routes.FirstOrDefault(r => r.RouteID == selectedRouteID);
			//var viewModel = new SeatViewModel
			//{
			//	SelectedRouteID = selectedRouteID,
			//	SelectedRoute = selectedRoute,
			//	Routes = c.Routes.ToList() 
			//};

			return View();
        }
    }
}

WebProje/Views/Customer/Index.cshtml
@model IEnumerable<EntityLayer.Concrete.Route>
@* @model EntityLayer.Concrete.SeatViewModel *@

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title>Booking Form HTML Template</title>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=PT+Sans:400" rel="stylesheet">

	<!-- Bootstrap -->
	<link type="text/css" rel="stylesheet" href="~/colorlib-booking-5/css/bootstrap.min.css" />

	<!-- Custom stlylesheet -->
	<link type="text/css" rel="stylesheet" href="~/colorlib-booking-5/css/style.css" />

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

</head>

<body>
	<div id="booking" class="section">
		<div class="section-center">
			<div class="container">
				<div class="row">
					<div class="booking-form">
						<form method="post" asp-controller="Seat" asp-action="Index">
							<div class="row">
								<div class="col-md-6">
									<div class="form-group">
										<span class="form-label">Select A Route</span>
										<select class="form-control">
											@* <label asp-for="SelectedRouteID" class="form-label">Select A Route</label>
											<select asp-for="SelectedRouteID" class="form-control" required> *@
											@foreach (var item in Model)
											{
													@* <option value="@item.RouteID">
														@($"{item.RouteName} - {item.TakeOff} - {item.Landing} - {item.DateTime}")
													</option> *@
												 <option> @Html.DisplayFor(modelItem=>item.RouteName)-
													@Html.DisplayFor(modelItem=>item.TakeOff)-
													@Html.DisplayFor(modelItem=>item.Landing)-
													@Html.DisplayFor(modelItem=>item.DateTime)
												</option> 
                                            }
                                        </select>
										
									</div>
                                </div>
								<button class="submit-btn" type="submit">Select</button>
							</div>
							
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>