WebProje/Controllers/AdminCustomerController.cs
using BusinessLayer.Abstract;
using BusinessLayer.Concrete;
using BusinessLayer.Validations;
using DataAccessLayer.EntityFramework;
using DataAccessLayer.Migrations;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace WebProje.Controllers
{
    [Authorize]
    public class AdminCustomerController : Controller
    {
        CustomerManager cm = new CustomerManager(new EFICustomer());
        //RouteManager rm = new RouteManager(new EfIRoute());
		//

		public IActionResult Index()
        {
            var customers = cm.GetList();

            return View(customers);
        }
        [HttpGet]

		public IActionResult AddCustomer()
        {
            return View();
        }
        [HttpPost]

		public IActionResult AddCustomer(Customer customer)
        {
            if (ModelState.IsValid)
            {
                cm.CustomerAdd(customer);
                return RedirectToAction("Index");
            }
            else
            {
                TempData["msj"] = "Ekleme başarısız";

                return View(customer);
            }

        }

		public IActionResult DeleteCustomer(int? id)
        {
            if (id == null)
            {
                return View("CustomerError");
            }
            else
            {
                var customervalue = cm.GetCustomer(id);

                cm.CustomerDelete(customervalue);

                return RedirectToAction("Index");
            }
        }
        [HttpGet]

		public IActionResult EditCustomer(int? id)
        {
            if (id == null || cm == null)
            {
                return NotFound("Error");
            }
            else
            {
                var customervalue = cm.GetCustomer(id);

                return View(customervalue);
            }
        }
        [HttpPost]

		public IActionResult EditCustomer(int? id, Customer customer)
        {
            if (id != customer.CustomerID)
            {
                TempData["hata"] = "ID'ler eşleşmiyor";
                return View("CustomerError");
            }
            else
            {
                if (ModelState.IsValid)
                {
                    cm.CustomerUpdate(customer);

                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["msj"] = "Ekleme başarısız";
                    return View(customer);
                }
            }
        }
        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Login", "Access");
        }
        //public IActionResult DetailsCustomer(int? id,Customer customer,EntityLayer.Concrete.Route route)
        //{


        //    if (id != customer.CustomerID || id != route.CustomerID)
        //    {
        //        return NotFound("id eslesmedi");
        //    }
        //    else
        //    {
        //        string customerid = cm.GetCustomer(id).ToString();
        //        string routeid = rm.GetRoute(id).CustomerID.ToString();

        //        if (customerid == routeid)
        //        {
        //            return View();
        //        }
        //        else
        //        {
        //            return NotFound("Error");
        //        }
        //    }
        //}
    }
}

WebProje/Views/AdminCustomer/AddCustomer.cshtml
@model EntityLayer.Concrete.Customer
<h3 style="color:red;">@TempData["msj"]</h3>
@{
    ViewData["Title"] = "AddCustomer";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>New Customer</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddCustomer">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CustomerName" class="control-label"></label>
                <input asp-for="CustomerName" class="form-control" />
                <span asp-validation-for="CustomerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerSurname" class="control-label"></label>
                <input asp-for="CustomerSurname" class="form-control" />
                <span asp-validation-for="CustomerSurname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerPassword" class="control-label"></label>
                <input asp-for="CustomerPassword" class="form-control" />
                <span asp-validation-for="CustomerPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerEmail" class="control-label"></label>
                <input asp-for="CustomerEmail" class="form-control" />
                <span asp-validation-for="CustomerEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerPhoneNumber" class="control-label"></label>
                <input asp-for="CustomerPhoneNumber" class="form-control" />
                <span asp-validation-for="CustomerPhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Add Customer" class="btn btn-success"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WebProje/Views/AdminCustomer/DetailsCustomer.cshtml
@model EntityLayer.Concrete.Route

@{
    ViewData["Title"] = "DetailsCustomer";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";

}

<h1>DetailsCustomer</h1>

<div>
    <h4>Route</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RouteName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RouteName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TakeOff)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TakeOff)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Landing)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Landing)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customer.CustomerEmail)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.RouteID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebProje/Views/AdminCustomer/EditCustomer.cshtml
@model EntityLayer.Concrete.Customer

@{
    ViewData["Title"] = "EditCustomer";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Edit Customer</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditCustomer">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CustomerID" />
            <div class="form-group">
                <label asp-for="CustomerName" class="control-label"></label>
                <input asp-for="CustomerName" class="form-control" />
                <span asp-validation-for="CustomerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerSurname" class="control-label"></label>
                <input asp-for="CustomerSurname" class="form-control" />
                <span asp-validation-for="CustomerSurname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerPassword" class="control-label"></label>
                <input asp-for="CustomerPassword" class="form-control" />
                <span asp-validation-for="CustomerPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerEmail" class="control-label"></label>
                <input asp-for="CustomerEmail" class="form-control" />
                <span asp-validation-for="CustomerEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerPhoneNumber" class="control-label"></label>
                <input asp-for="CustomerPhoneNumber" class="form-control" />
                <span asp-validation-for="CustomerPhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WebProje/Views/AdminCustomer/Index.cshtml
@model IEnumerable<EntityLayer.Concrete.Customer>
@* <h3 style="color:red;">@TempData["msj"]</h3> *@
@{
    // ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h1>Customers</h1>


<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model=>model.CustomerID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CustomerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CustomerSurname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CustomerPassword)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CustomerEmail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CustomerPhoneNumber)
            </th>
            <th>
                Options
            </th>

        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            @foreach (var item in Model)
            {
                <tr>
                    <th>
                        @Html.DisplayFor(modelItem=>item.CustomerID)
                    </th>
                    <td>
                        @Html.DisplayFor(modelItem => item.CustomerName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CustomerSurname)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CustomerPassword)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CustomerEmail)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CustomerPhoneNumber)
                    </td>

                    <td>
                        <a asp-controller="AdminCustomer" asp-action="EditCustomer" asp-route-id="@item.CustomerID" method="post" class="btn btn-info">Edit</a>
                        <a asp-controller="AdminCustomer" asp-action="DetailsCustomer" asp-route-id="@item.CustomerID" class="btn btn-warning">Route</a>
                        <a asp-controller="AdminCustomer" asp-action="DeleteCustomer" asp-route-id="@item.CustomerID" method="post" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
                @*  <div>
        <a asp-action="AdminCustomer" asp-action="AddCustomer" asp-route-id="@item.CustomerID" method="post" class="btn btn-success">New Customer</a>
        </div> *@
            }
        }


    </tbody>

</table>
@* <a href="/AdminCustomer/AddCustomer" class="btn btn-success">New Customer</a> *@
<div>
    <a asp-controller="AdminCustomer" asp-action="AddCustomer" method="post" class="btn btn-success">New Customer</a>
</div>