WebProje/Controllers/AccessController.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using EntityLayer.Concrete;
using DataAccessLayer.Concrete;

namespace WebProje.Controllers
{
    public class AccessController : Controller
    {
        Context c = new Context();
        [HttpGet]
        public IActionResult Login()
        {
            ClaimsPrincipal claimAdmin = HttpContext.User; //if already logged in
            if(claimAdmin.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "AdminCustomer");
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model) //-------->LoginViewModeli Admin admin ile değiştir
        {
            var adminuser = c.Admins.FirstOrDefault(x => x.AdminEmail == model.Email && x.AdminPassword == model.Password);
            if (adminuser != null)
            {
                List<Claim> claims = new List<Claim>()
                {
                    new Claim(ClaimTypes.NameIdentifier,model.Email),
                    new Claim("OtherProperties","Role")
                };
                ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims,
                    CookieAuthenticationDefaults.AuthenticationScheme);

                AuthenticationProperties properties = new AuthenticationProperties()
                {
                    AllowRefresh = true,
                    IsPersistent = model.KeepLoggedIn
                };

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                    new ClaimsPrincipal(claimsIdentity), properties);
                return RedirectToAction("Index","AdminCustomer");
            }
            ViewData["ValidateMessage"] = "Admin not found";
            return View();
        }
    }
}

WebProje/Controllers/CustomerLoginController.cs
using DataAccessLayer.Concrete;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace WebProje.Controllers
{
    public class CustomerLoginController : Controller
    {
        Context c = new Context();
        [HttpGet]
        public IActionResult Login()
        {
            ClaimsPrincipal claimCustomer = HttpContext.User; //if already logged in
            if (claimCustomer.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Customer");
            }
            return View();

        }
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            var customeruser = c.Customers.FirstOrDefault(x => x.CustomerEmail == model.Email && x.CustomerPassword == model.Password);
            if (customeruser != null)
            {
                List<Claim> claims = new List<Claim>()
                {
                    new Claim(ClaimTypes.NameIdentifier,model.Email),
                    new Claim("OtherProperties","Role")
                };
                ClaimsIdentity claimscustomerIdentity = new ClaimsIdentity(claims,
                    CookieAuthenticationDefaults.AuthenticationScheme);

                AuthenticationProperties properties = new AuthenticationProperties()
                {
                    AllowRefresh = true,
                    IsPersistent = model.KeepLoggedIn
                };

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                    new ClaimsPrincipal(claimscustomerIdentity), properties);
                return RedirectToAction("Index", "Customer");
            }
            ViewData["ValidateMessage"] = "Customer not found";
            return View();
            
        }
    }
}

WebProje/Views/Access/Login.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

@model EntityLayer.Concrete.LoginViewModel;
@{
  Layout = null;
}
<doctype html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="~/login-form-11/css/style.css">

</head>
<body>
    <section class="ftco-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6 text-center mb-5">
                    <h2 class="heading-section">Admin Login</h2>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-7 col-lg-5">
                    <div class="login-wrap p-4 p-md-5">
                        <div class="icon d-flex align-items-center justify-content-center">
                            <span class="fa fa-user-o"></span>
                        </div>
                        <h3 class="text-center mb-4">Login</h3>
                        <form asp-controller="Access" asp-action="Login" method="post">
                            <div class="form-group">
                                <input type="email" class="form-control rounded-left" name="Email" placeholder="Username" required>

                            </div>
                            <div class="form-group d-flex">
                                <input type="password" class="form-control rounded-left" name="Password" placeholder="Password" required>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="form-control btn btn-primary rounded submit px-3">Login</button>
                            </div>
                            <div class="form-group d-md-flex">
                                <div class="w-50">
                                    <label class="checkbox-wrap checkbox-primary">
                                        Remember Me
                                        <input type="checkbox" asp-for="KeepLoggedIn"> 
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                                <div class="w-50 text-md-right">
                                    <a href="#">Forgot Password</a>
                                </div>
                            </div>
                            @if(ViewData["ValidateMessage"]!=null)
                            {
                                <br />
                                <br />
                                <label>@ViewData["ValidateMessage"]</label>
                            
                            }
                        </form>
                            <a asp-controller="CustomerLogin" asp-action="Login" class="btn btn-primary">Customer Login</a>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <script src="js/jquery.min.js"></script>
    <script src="js/popper.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/main.js"></script>

</body>
</html>