WebProje/Controllers/RouteController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
//using Route = EntityLayer.Concrete.Route;

namespace WebProje.Controllers
{
    public class RouteController : Controller
    {
        RouteManager rm= new RouteManager(new EfIRoute());
        CustomerManager cm=new CustomerManager(new EFICustomer());
        public IActionResult Index()
        {
            var routevalues=rm.GetRoutes();
            return View(routevalues);
        }
        [HttpGet]
        public IActionResult AddRoute()
        {
            List<SelectListItem> routes = (from x in cm.GetList()
                                           select new SelectListItem
                                           {
                                               Text=x.CustomerName,
                                               Value=x.CustomerID.ToString(),

                                           }).ToList();
            ViewBag.vrt=routes;
            return View();
        }
        [HttpPost]
        public IActionResult AddRoute(EntityLayer.Concrete.Route route) 
        {
            rm.RouteAdd(route);
            return RedirectToAction("Index");
        }

        [Route("RouteDelete/{id:int}")]
        public IActionResult DeleteRoute(int id)
        {
            var routevalue = rm.GetRoute(id);

            rm.RouteDelete(routevalue);

            return RedirectToAction("Index");
        }
        [HttpGet]
        [Route("RouteEdit/{id:int}")]
        public IActionResult EditRoute(int id)
        {
            var routevalue = rm.GetRoute(id);

            return View(routevalue);
        }
        [HttpPost]
        [Route("RouteEdit/{id:int}")]
        public IActionResult EditRoute(EntityLayer.Concrete.Route route)
        {
            rm.RouteUpdate(route);

            return RedirectToAction("Index");
        }
    }
}

WebProje/Views/Route/AddRoute.cshtml
@model EntityLayer.Concrete.Route

@{
    ViewData["Title"] = "AddRoute";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Add Route</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddRoute">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RouteName" class="control-label"></label>
                <input asp-for="RouteName" class="form-control" />
                <span asp-validation-for="RouteName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TakeOff" class="control-label"></label>
                <input asp-for="TakeOff" class="form-control" />
                <span asp-validation-for="TakeOff" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Landing" class="control-label"></label>
                <input asp-for="Landing" class="form-control" />
                <span asp-validation-for="Landing" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateTime" class="control-label"></label>
                <input asp-for="DateTime" class="form-control" />
                <span asp-validation-for="DateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerID" class="control-label"></label>
                <select asp-for="CustomerID" class ="form-control" asp-items="ViewBag.vrt"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WebProje/Views/Route/EditRoute.cshtml
@model EntityLayer.Concrete.Route

@{
    ViewData["Title"] = "EditRoute";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>EditRoute</h1>

<h4>Route</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditRoute">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="RouteID" />
            <div class="form-group">
                <label asp-for="RouteName" class="control-label"></label>
                <input asp-for="RouteName" class="form-control" />
                <span asp-validation-for="RouteName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TakeOff" class="control-label"></label>
                <input asp-for="TakeOff" class="form-control" />
                <span asp-validation-for="TakeOff" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Landing" class="control-label"></label>
                <input asp-for="Landing" class="form-control" />
                <span asp-validation-for="Landing" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateTime" class="control-label"></label>
                <input asp-for="DateTime" class="form-control" />
                <span asp-validation-for="DateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerID" class="control-label"></label>
                <select asp-for="CustomerID" class="form-control" asp-items="ViewBag.vrt"></select>
                <span asp-validation-for="CustomerID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WebProje/Views/Route/Index.cshtml
@model IEnumerable<EntityLayer.Concrete.Route>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h1>Routes</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model=>model.RouteID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RouteName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TakeOff)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Landing)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Customer)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {


            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.RouteID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RouteName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TakeOff)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Landing)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateTime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CustomerID)
                    </td>
                    <td>
                        <a asp-controller="Route" asp-action="EditRoute" asp-route-id="@item.RouteID" method="post" class="btn btn-info">Edit</a>
                        <a href="#" class="btn btn-warning">Plane</a>
                        <a asp-controller="Route" asp-action="DeleteRoute" asp-route-id="@item.RouteID" method="post" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>
<a href="/Route/AddRoute" class="btn btn-info">New Route</a>